export const PRODUCT_CATAGORY_LIST_REQUEST = 'PRODUCT_CATAGORY_LIST_REQUEST';
export const PRODUCT_CATAGORY_LIST_SUCCESS = 'PRODUCT_CATAGORY_LIST_SUCCESS';
export const PRODUCT_CATAGORY_LIST_FAIL = 'PRODUCT_CATAGORY_LIST_FAIL';

export const PRODUCT_CATAGORY_DETAILS_REQUEST = 'PRODUCT_CATAGORY_DETAILS_REQUEST';
export const PRODUCT_CATAGORY_DETAILS_SUCCESS = 'PRODUCT_CATAGORY_DETAILS_SUCCESS';
export const PRODUCT_CATAGORY_DETAILS_FAIL = 'PRODUCT_CATAGORY_DETAILS_FAIL';
